# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  liquiddemocracyserver:
    image: liquiddemocracy
    ports:
      - "5093:5093"

  liquiddemocracyweb:
    image: liquiddemocracyweb
    ports:
      - "3000:3000"
      
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
        TrustServerCertificate: True
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
