# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  liquiddemocracyserver:
    image: liquiddemocracy
    ports:
      - "5000:5000"

  liquiddemocracyweb:
    image: liquiddemocracyweb
    ports:
      - "3000:3000"
